### ISSUE TITLE
fb_match_lineups() not returning correct team

### ISSUE THREAD

**Issue by vennanalysis** [JaseZiv/worldfootballR#221]
I am using the fb_match_lineups() function on a range of World Cup Qualifier URLs and the **team** column does not seem to be correct.

For some entries the Home and Away team are mixed up, for other entries it shows "Major League Soccer"

Any help would be appreciated

Cheers,
Daniel

**Comment by pedroorden** [comment]
I had the same problem but I checked the package changelog and I saw that this error is a recognized bug https://jaseziv.github.io/worldfootballR/news/index.html

**Comment by JaseZiv** [comment]
> I am using the fb_match_lineups() function on a range of World Cup Qualifier URLs and the **team** column does not seem to be correct.
> 
> For some entries the Home and Away team are mixed up, for other entries it shows "Major League Soccer"
> 
> Any help would be appreciated
> 
> Cheers, Daniel

As @pedroorden stated, this issue should have been resolved.

Make sure you’ve installed the latest dev version.

Let me know if there’s still issues.

**Comment by vennanalysis** [comment]
Appreciate the responses - apologies for not checking the github version - my first time posting here

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vennanalysis** [comment]
I installed via GitHub but still have the same issue (see below).

Using sessionInfo() I have the following version - worldfootballR_0.6.1.8000

`fb_match_lineups(match_url = "https://fbref.com/en/matches/4b84070f/Jamaica-Mexico-January-27-2022-WCQ----CONCACAF-M")`

![image](https://user-images.githubusercontent.com/118441801/202586361-db34b04a-8754-4991-88c8-c80fadf38909.png)

**Comment by JaseZiv** [comment]
Sorry about this... 

I've just tested myself and it looks like FBref have yet again changed their HTML and reintroduced this but...

I will address it shortly.

Sorry for the hassle

**Comment by JaseZiv** [comment]
@vennanalysis install the latest dev version - this should now be fixed.

Thanks

**Comment by rostagg** [comment]
Hey great script these are so helpful!

Just wanted to say that this issue is occurring when using fb_advanced_match_stats too

`test <- fb_advanced_match_stats(match_url = "https://fbref.com/en/matches/1b496cc1/Arsenal-Nottingham-Forest-October-30-2022-Premier-League",stat_type = "summary","player")`

![image](https://user-images.githubusercontent.com/118491747/202794700-d82615c4-8445-44ba-bdea-48ccae16f546.png)
