### ISSUE TITLE
Issue with 'fb_player_season_stats' function.

### ISSUE THREAD

**Issue by JonnyHorsley** [JaseZiv/worldfootballR#33]
Issues with 'fb_player_season_stats' function for players who are listed under a club (using 'fb_player_urls' function), but it is their first season, or they are yet to make an appearance. Please see attached reproducible example.
[Issue_Reproducible_Example.R.zip](https://github.com/JaseZiv/worldfootballR/files/6503236/Issue_Reproducible_Example.R.zip)

**Comment by JaseZiv** [comment]
The code has been fixed for the anomalies identified, with some functionality improvements, namely that the function is now vectorised:

```
# these URLs were provided in the MRE with issues:
old_problem_urls <- c("https://fbref.com/en/players/46dc146a/Claudio-Ofosu", 
                      "https://fbref.com/en/players/3bd54918/Joe-Grey",
                      "https://fbref.com/en/players/042f690f/Brad-Young")

# Code is now vectorised:
old_problem_data <- fb_player_season_stats(player_url = old_problem_urls, stat_type = "playing_time")
```
![image](https://user-images.githubusercontent.com/31471783/118958465-cc66db00-b9a4-11eb-9668-f6f69f4e824d.png)


This functionality now means you won't need to loop as you had provided in the MRE:

```
#### No longer need to loop ####

#Get Pools players' URLs
pools_2021_player_URLs = fb_player_urls("https://fbref.com/en/squads/2af58c3d/Hartlepool-United-Stats")

# Pass all Hartlepool player URLs
pools_player_seasons <- fb_player_season_stats(player_url = pools_2021_player_URLs, stat_type = "playing_time")
```
![image](https://user-images.githubusercontent.com/31471783/118958692-fd471000-b9a4-11eb-8549-e9200a6ea60e.png)

**Comment by JonnyHorsley** [comment]
Great work, thanks!

**Comment by ChrisH1997** [comment]
Unfortunaly, fb_player_season_stats() is still failing for some players if the stat-category can't be found on their fbref page.
Example:
`fb_player_season_stats("https://fbref.com/en/players/88ced02c/Cameron-Carter-Vickers", stat_type = "passing")`
`Error in .f(.x[[1L]], .y[[1L]], ...) : check stat type`
`fb_player_season_stats("https://fbref.com/en/players/881e5db7/Joel-Castro-Pereira", stat_type = "shooting")`
`Error in .f(.x[[1L]], .y[[1L]], ...) : check stat type`
Can be solved by using map(..., possibly(fb_player_season_stats, NA), ...), which takes longer so it would be really nice if this could be fixed.

**Comment by JaseZiv** [comment]
@ChrisH1997 this should hopefully be fixed with version 0.3.2.2.

Thanks for identifying.
